export const colombiaData = [
  { departamento: 'Amazonas', ciudades: ['Leticia', 'Puerto Nariño'] },
  {
    departamento: 'Antioquia',
    ciudades: [
      'Medellín',
      'Bello',
      'Envigado',
      'Itagüí',
      'Sabaneta',
      'Rionegro',
      'Apartadó',
      'Caldas',
      'Copacabana',
      'La Estrella',
    ],
  },
  { departamento: 'Arauca', ciudades: ['Arauca', 'Arauquita', 'Saravena', 'Tame'] },
  {
    departamento: 'Atlántico',
    ciudades: [
      'Barranquilla',
      'Soledad',
      'Malambo',
      'Sabanalarga',
      'Puerto Colombia',
    ],
  },
  {
    departamento: 'Bogotá D.C.',
    ciudades: ['Bogotá'],
  },
  {
    departamento: 'Bolívar',
    ciudades: ['Cartagena de Indias', 'Magangué', 'El Carmen de Bolívar', 'Turbaco'],
  },
  { departamento: 'Boyacá', ciudades: ['Tunja', 'Duitama', 'Sogamoso', 'Chiquinquirá'] },
  { departamento: 'Caldas', ciudades: ['Manizales', 'La Dorada', 'Chinchiná', 'Villamaría'] },
  { departamento: 'Caquetá', ciudades: ['Florencia', 'San Vicente del Caguán'] },
  { departamento: 'Casanare', ciudades: ['Yopal', 'Aguazul', 'Villanueva'] },
  {
    departamento: 'Cauca',
    ciudades: ['Popayán', 'Santander de Quilichao', 'Puerto Tejada'],
  },
  { departamento: 'Cesar', ciudades: ['Valledupar', 'Aguachica', 'Agustín Codazzi'] },
  { departamento: 'Chocó', ciudades: ['Quibdó', 'Istmina'] },
  { departamento: 'Córdoba', ciudades: ['Montería', 'Cereté', 'Sahagún', 'Lorica'] },
  {
    departamento: 'Cundinamarca',
    ciudades: [
      'Soacha',
      'Fusagasugá',
      'Facatativá',
      'Zipaquirá',
      'Chía',
      'Girardot',
    ],
  },
  { departamento: 'Guainía', ciudades: ['Inírida'] },
  { departamento: 'Guaviare', ciudades: ['San José del Guaviare'] },
  { departamento: 'Huila', ciudades: ['Neiva', 'Pitalito', 'Garzón', 'La Plata'] },
  {
    departamento: 'La Guajira',
    ciudades: ['Riohacha', 'Maicao', 'Uribia', 'San Juan del Cesar'],
  },
  { departamento: 'Magdalena', ciudades: ['Santa Marta', 'Ciénaga', 'Fundación'] },
  { departamento: 'Meta', ciudades: ['Villavicencio', 'Acacías', 'Granada'] },
  { departamento: 'Nariño', ciudades: ['Pasto', 'Tumaco', 'Ipiales'] },
  {
    departamento: 'Norte de Santander',
    ciudades: ['Cúcuta', 'Ocaña', 'Pamplona', 'Villa del Rosario'],
  },
  { departamento: 'Putumayo', ciudades: ['Mocoa', 'Puerto Asís', 'Orito'] },
  { departamento: 'Quindío', ciudades: ['Armenia', 'Calarcá', 'Montenegro'] },
  {
    departamento: 'Risaralda',
    ciudades: ['Pereira', 'Dosquebradas', 'Santa Rosa de Cabal'],
  },
  {
    departamento: 'San Andrés y Providencia',
    ciudades: ['San Andrés'],
  },
  {
    departamento: 'Santander',
    ciudades: [
      'Bucaramanga',
      'Floridablanca',
      'Girón',
      'Piedecuesta',
      'Barrancabermeja',
    ],
  },
  { departamento: 'Sucre', ciudades: ['Sincelejo', 'Corozal', 'Tolú'] },
  { departamento: 'Tolima', ciudades: ['Ibagué', 'Espinal', 'Melgar'] },
  {
    departamento: 'Valle del Cauca',
    ciudades: [
      'Cali',
      'Buenaventura',
      'Palmira',
      'Tuluá',
      'Buga',
      'Cartago',
      'Jamundí',
    ],
  },
  { departamento: 'Vaupés', ciudades: ['Mitú'] },
  { departamento: 'Vichada', ciudades: ['Puerto Carreño'] },
];
